CREATE TABLE Users(
	uname VARCHAR(20) PRIMARY KEY,
	passwd VARCHAR(20),
	role VARCHAR(10)
);

CREATE TABLE Clients(
	cID INT NOT NULL PRIMARY KEY
            GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	cName VARCHAR(50),
	cAddress VARCHAR(100),
	cType VARCHAR(10),
	uName VARCHAR(20) REFERENCES Users(uname)
);

CREATE TABLE employee(
	eID INT NOT NULL PRIMARY KEY
            GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	eName VARCHAR(50),
	eAddress VARCHAR(100),
	uName VARCHAR(20) REFERENCES Users(uname)
);

CREATE TABLE Operations(
    oID INT NOT NULL PRIMARY KEY
            GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    eID INT REFERENCES Employee(eID),
    cID INT REFERENCES Clients(cID),
    oDate DATE,
    oTime TIME,
    nSlot INT,
    -- NOTE: Change this to DECIMAL at earliest opportunity --Josh
    charge FLOAT
);